title: DDR
description: SKSE64 plugin for runtime Skyrim dialogue replacement
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

url: "https://krisv-777.github.io"
baseurl: "/Dynamic-Dialogue-Replacer"
aux_links:
  "GitHub":
    - "https://github.com/KrisV-777/Dynamic-Dialogue-Replacer"
aux_links_new_tab: true

search_enabled: true
footer_content: "Dynamic Dialogue Replacer &mdash; released under <a href=\"../COPYING\">GPL-3.0</a>."
heading_anchors: true

callouts:
  note:
    color: blue
  warning:
    color: yellow
